name: whatsapp-summarizer
services:
- name: api
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/whatsapp-summarizer-backend
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /
    port: 3000